### PR TITLE
:memo: support tsx :rose:

### PR DESCRIPTION
**Pull request by basarat**

### CODE REVIEW

**Comment by blakeembrey** [comment]
@basarat Thanks for the update. It definitely does work, I'll look into the errors - looks like an issue with finding the bundled definitions from modules (damn it, I need to finish TSD to solve this already).

**Comment by blakeembrey** [comment]
@basarat Quick unrelated question - how does the `typings` field work in `package.json` and why wouldn't it automatically try to load `.d.ts` based on the `"main"` field? Just run into this publishing a patch to `tsconfig` (whoops).

**Comment by basarat** [comment]
> how does the typings field work in package.json and why wouldn't it automatically try to load .d.ts based on the "main" field

There is no reading of `main`. `typings` is a pseudonym version for typescript. If one is using index then neither is required. 

Otherwise specify `main` as well as `typings` (I've only tested without the `.d.ts` extension).

**Comment by basarat** [comment]
Docs: https://basarat.gitbooks.io/typescript/content/docs/node/nodejs.html

Demo: https://github.com/basarat/csx/blob/gh-pages/package.json

PS: I didn't design this and I was confused too https://github.com/Microsoft/TypeScript/issues/4613 

`main` should probably be supported but I haven't raised a :crossed_flags:

**Comment by blakeembrey** [comment]
Yeah, I think there's some more work to do on it so I'm going to see what happens with TSD#future - I've ended up compiling it down (with support for `typings`) into a single file with paths so you can import from modules directly. There's a lot in TypeScript that needs to work and I think can be solved in user land before I make any sweeping statements - for example, aliases (solved in TypeScript-ish) but not `browser` field.

Anyway, looks like I assumed `typings` field incorrectly and I'll release another patch for this to compile properly. `typings` is pretty nice for the majority of cases :smile:

**Pull request merged**
